"""
Utility helpers: report generation, JSON/Markdown export, and misc formatting.
"""
import json
import os
from datetime import datetime
from typing import List

from models.review_schema import ReviewComment, RepoStats


def review_to_dict(r: ReviewComment) -> dict:
    """Converts ReviewComment to dict — compatible with Pydantic v1 and v2."""
    try:
        return r.model_dump()   # Pydantic v2
    except AttributeError:
        return r.dict()         # Pydantic v1


def reviews_to_dict(reviews: List[ReviewComment]) -> List[dict]:
    return [review_to_dict(r) for r in reviews]


def generate_json_report(
    reviews: List[ReviewComment],
    stats: RepoStats,
    output_path: str = None,
) -> str:
    """Generates a JSON report. Returns the JSON string; optionally writes to file."""
    report = {
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "repository": stats.repo_url,
        "summary": {
            "total_files": stats.total_files,
            "total_functions": stats.total_functions,
            "total_classes": stats.total_classes,
            "total_lines": stats.total_lines,
            "issues_found": stats.issues_found,
            "high_severity": stats.high_severity,
            "medium_severity": stats.medium_severity,
            "low_severity": stats.low_severity,
        },
        "reviews": reviews_to_dict(reviews),
    }

    json_str = json.dumps(report, indent=2)

    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w") as f:
            f.write(json_str)

    return json_str


def severity_emoji(severity: str) -> str:
    mapping = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🔵", "Info": "⚪"}
    return mapping.get(severity, "⚪")


def confidence_emoji(confidence: int) -> str:
    if confidence >= 80:
        return "✅"
    elif confidence >= 50:
        return "⚠️"
    return "❓"


def generate_markdown_report(
    reviews: List[ReviewComment],
    stats: RepoStats,
    output_path: str = None,
) -> str:
    """Generates a GitHub-style Markdown review report."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# 🤖 AI Code Review Report",
        "",
        f"> **Repository:** `{stats.repo_url}`  ",
        f"> **Generated:** {now}",
        "",
        "---",
        "",
        "## 📊 Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Files Scanned | {stats.total_files} |",
        f"| Functions Analyzed | {stats.total_functions} |",
        f"| Classes Found | {stats.total_classes} |",
        f"| Total Lines | {stats.total_lines} |",
        f"| Issues Found | **{stats.issues_found}** |",
        f"| 🔴 High/Critical | {stats.high_severity} |",
        f"| 🟡 Medium | {stats.medium_severity} |",
        f"| 🔵 Low/Info | {stats.low_severity} |",
        "",
        "---",
        "",
        "## 🔍 Review Comments",
        "",
    ]

    if not reviews:
        lines.append("*No issues found — the code looks clean!* 🎉")
    else:
        for i, r in enumerate(reviews, 1):
            sev = severity_emoji(r.severity)
            conf = confidence_emoji(r.confidence)
            verify_tag = " `⚠️ VERIFY THIS`" if r.confidence < 50 else ""
            lines += [
                f"### {i}. {sev} `{r.issue_type}` — `{r.severity}`{verify_tag}",
                "",
                f"- **File:** `{r.file}`",
                f"- **Function:** `{r.function}`",
                f"- **Confidence:** {conf} {r.confidence}%  ",
                f"- **Lines:** {r.line_start}–{r.line_end}",
                "",
                "**Issue:**  ",
                r.comment,
                "",
                "**Suggestion:**  ",
                r.suggestion,
                "",
                "---",
                "",
            ]

    lines += ["", "*Generated by [AI Code Review Agent](https://github.com)*"]
    markdown_str = "\n".join(lines)

    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w") as f:
            f.write(markdown_str)

    return markdown_str